apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: appset
spec:
  generate:
    command:
      - bash
      - -co
      - pipefail
      - |
        # Create tracking file for this application
        (cd /cmp/list; [[ "$ARGOCD_APP_NAME" == *_* ]] && touch "$ARGOCD_APP_NAME" || touch "$(</run/secrets/kubernetes.io/serviceaccount/namespace)_$ARGOCD_APP_NAME")

        # Generate individual applications from ApplicationSet spec
        echo "$PARAM_SPEC" | yq '{ "metadata": { "name": "-" }, "spec": . }' | argocd appset generate /dev/stdin -o yaml | yq '.[] | split_doc'
