apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: appset
spec:
  generate:
    command:
      - bash
      - -co
      - pipefail
      - |
        (cd /appset/list; touch "$ARGOCD_APP_NAMESPACE:$ARGOCD_APP_NAME")
        echo "$ARGOCD_ENV_SPEC" | yq '{ "metadata": { "name": "-" }, "spec": . }' | argocd --core appset generate /dev/stdin -o yaml | yq '.[] | split_doc'
